### ISSUE TITLE
Add img as as alternative builder

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/skaffold#242] opened 2018-03-20 09:24 UTC
[img](https://github.com/genuinetools/img) is an alternative to Docker build daemon that uses Dockerfile and produces OCI images, it maybe a good idea to consider adding it as an option.

cc @jessfraz

**Comment by r2d4** [comment] 2018-03-20 15:40
I'll close this as a dupe of https://github.com/GoogleCloudPlatform/skaffold/issues/138

In short, yes, its something we'd absolutely like to support.

**Closed by r2d4** 2018-03-20 15:40 UTC
