### ISSUE TITLE
No-Manifest example doesn't work

### ISSUE THREAD

**Issue by Trane9991** [GoogleCloudPlatform/skaffold#181] opened 2018-03-10 10:58 UTC
Trying to run an example from [no-manifest](https://github.com/GoogleCloudPlatform/skaffold/tree/master/examples/no-manifest) folder fails with:
`ERRO[0000] run: getting skaffold config: getting k8s client: Error creating kubeConfig: invalid configuration: no configuration has been provided`

**Comment by r2d4** [comment] 2018-03-10 17:36
Hm, thats an error getting your kubeconfig.  You'll still need kubectl installed and configured with your cluster context. Does a `kubectl version` work?

**Comment by Trane9991** [comment] 2018-03-10 18:53
Yep, with configured `kubectl` everything fine.
I just expected that `no-manifest` will not require kubeconfig, since no deployment is configured.

**Comment by dlorenc** [comment] 2018-03-10 20:53
Ah, yeah the no manifest example still depends on kubectl for the final "apply" step. Unfortunately that code isn't easily usable outside of kubectl right now.

I think long term we should try to use the client libraries directly, but that's blocked on some upstream work to make kubectl apply usable from the libraries.

In the short term we'll improve this error message with #40. Closing as a dupe of that.

**Closed by dlorenc** 2018-03-10 20:53 UTC
Labels: bug
